name: test_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  built_value: ^6.1.4
  built_collection: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
      - example/assets/
      - example/assets/sub/
      - example/assets/sub/ignore1/
      - example/assets/sub/ignore2/
      - example/assets/sub/sub/
      - example/assets/sub2/sub2.txt
      - example/assets/sub2/

  fonts:
     - family: H6allo%§ä
       fonts:
         - asset: fonts/temp-Regular.ttf
     - family: Schyler
       fonts:
         - asset: fonts/Schyler-Regular.ttf
         - asset: fonts/Schyler-Italic.ttf
           style: italic
     - family: Trajan Pro
       fonts:
         - asset: fonts/TrajanPro.ttf
         - asset: fonts/TrajanPro_Bold.ttf
           weight: 700
