name: r_flutter
version: 0.17.2
author: Tim Freiheit
description: 

homepage: 
environment:
  sdk: '>=2.0.0-dev.33.0 <3.0.0'

dependencies:
  analyzer: '>=0.33.0-alpha.0 <0.34.0'
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  path: '>=0.9.0 <2.0.0'
  yaml: ^2.1.15
  recase: ^2.0.1
dev_dependencies:
  test: ^1.2.0
